apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: jaeger-inmemory-instance
spec:
  image: jaegertracing/jaeger:latest
  ports:
  - name: jaeger
    port: 16686
  config:
    service:
      extensions: [jaeger_storage, jaeger_query]
      pipelines:
        traces:
          receivers: [otlp]    
          exporters: [jaeger_storage_exporter]
    extensions:
      jaeger_query:
        storage:
          traces: memstore
      jaeger_storage:
        backends:
          memstore:
            memory:
              max_traces: 100000 # 메모리에 저장된 트레이스 양에는 제한이 없지만 다음을 통해 제한을 설정
        # metric_backends:
        #   some_metrics_storage:
        #     prometheus:
        #       endpoint: http://prometheus.default.svc.cluster.local:9090
        #       normalize_calls: true
        #       normalize_duration: true
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317 # 다른 port 사용 가능 
          http:
            endpoint: 0.0.0.0:4318 # 다른 port 사용 가능 
    exporters:
      jaeger_storage_exporter:
        trace_storage: memstore