apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rollout-bluegreen-hpa
  namespace: argo-rollouts
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rollout-bluegreen
  targetCPUUtilizationPercentage: 60