replicaCount: 2
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
  
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: nginx-alb
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: "ip"
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
          backend:
            servicePort: 80